// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVAhgk3Il50AmEHdc5Pqw50FQm7IlngZM',
    appId: '1:668988659866:web:c7344c3e70aab5fa3aa723',
    messagingSenderId: '668988659866',
    projectId: 'flutter-prep-19820',
    authDomain: 'flutter-prep-19820.firebaseapp.com',
    databaseURL: 'https://flutter-prep-19820-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-prep-19820.appspot.com',
    measurementId: 'G-3WKN6BPPG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw4r-yEaHGwF8av28EOOzjnGC4wd7OJ_8',
    appId: '1:668988659866:android:db28f2339b0dcf2e3aa723',
    messagingSenderId: '668988659866',
    projectId: 'flutter-prep-19820',
    databaseURL: 'https://flutter-prep-19820-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-prep-19820.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX8ontxNkk8AtgKIN4tr7bH3QjWJbNXpI',
    appId: '1:668988659866:ios:46f985f4e7dda0273aa723',
    messagingSenderId: '668988659866',
    projectId: 'flutter-prep-19820',
    databaseURL: 'https://flutter-prep-19820-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-prep-19820.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX8ontxNkk8AtgKIN4tr7bH3QjWJbNXpI',
    appId: '1:668988659866:ios:1289b5503efe8c6c3aa723',
    messagingSenderId: '668988659866',
    projectId: 'flutter-prep-19820',
    databaseURL: 'https://flutter-prep-19820-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-prep-19820.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
